export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_REPOS = 'FETCH_REPOS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';
export const FETCH_REPOS_ERROR = 'FETCH_REPOS_ERROR';
export const SET_LOADING = 'SET_LOADING';
